fix: soql builder save an empty result file
forcedotcom/salesforcedx-vscode pull request #4754
Opened 2023-03-27 15:45 UTC by floralan

### What does this PR do?

### What issues does this PR fix or reference?
#<Insert GitHub Issue>, @<Insert GUS WI>@

### Functionality Before
<insert gif and/or summary>

### Functionality After
<insert gif and/or summary>

2023-03-27 18:29 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
> +    fs.rm(testResultsDirPath, { recursive: true });
`(node:488) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead`

2023-03-27 18:33 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
> +    fs.rmSync(testResultsDirPath, { recursive: true });
`(node:488) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead`

2023-03-27 19:37 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
> +    fs.rmSync(testResultsDirPath, { recursive: true });
This is not a part of the fix, but something I noticed when looking at the test history.

2023-03-27 19:51 UTC, jgellin-sf approved these changes

2023-03-27 21:00 UTC, jonnyhork approved these changes
Looks good to me!

2023-03-29 14:55 UTC, randi274 commented on packages/salesforcedx-vscode-soql/test/jest/queryDataFileService.test.ts
> + * Copyright (c) 2022, salesforce.com, inc.
Small nit - 2023!

2023-03-29 20:04 UTC, floralan commented on scripts/setup-jest.ts
> +      showSaveDialog: jest.fn(),
Add `showSaveDialog` and `fs` in vs code stub.

2023-03-29 20:05 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/testUtilities.ts
> +const { workspaceContext = {}, channelService = {} } = soqlExports ?? {};
A quick fix for an edge case, but not been used in this PR.

2023-03-30 01:04 UTC, floralan commented on packages/salesforcedx-vscode-soql/src/queryDataView/queryDataFileService.ts
> +      await vscode.workspace.fs.writeFile(fileInfo, fileContent);
I added `await` here to run it synchronously. @randi274

2023-03-30 01:10 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
>      const jsonFileService = new TestFileService(
@randi274 I want to skip these two tests as we have the unit tests covering the `save()` function. 

I did another end-to-end test on Mac and Code Builder to confirm this fix is working for both. 

Another reason for skipping these two tests is this [error](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/4559036019/jobs/8042546932#:~:text=1)%20Query%20Data,ts%3A114%3A27)), which I spent 1 hr to debug but didn't have luck. Considering the limited time I have, I will create a WI so we can cycle back on this after GA.

2023-03-31 15:36 UTC, floralan commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
>      const jsonFileService = new TestFileService(
@randi274 Sounds good. Thank you for doing the QA!

2023-03-31 18:03 UTC, randi274 requested changes
Ok one more small change and we should be good to go!

2023-03-31 18:25 UTC, randi274 commented on packages/salesforcedx-vscode-soql/test/vscode-integration/queryDataView/queryDataFileService.test.ts
> -  it('should save json file to disk on save', async () => {
Reference for deleting this and making follow-up tests: W-12779641

2023-04-03 21:29 UTC, merged