docs: LWC Code Snippets
forcedotcom/salesforcedx-vscode pull request #5009
Opened 2023-08-01 20:14 UTC by mvogelgesang

### What does this PR do?
Updates links to Code Snippet files and adds mention of LWC Code Snippets to relevant page.

EN and JA files were split into separate commits.

### What issues does this PR fix or reference?
#5006 

### Functionality Before
<insert gif and/or summary>

### Functionality After
<insert gif and/or summary>

2023-08-01 20:52 UTC, CristiCanizales requested changes

2023-08-01 20:52 UTC, CristiCanizales commented on docs/_articles/ja/apex/writing.md
Hi! This should be in japanese as the rest of the file!

2023-08-01 20:52 UTC, CristiCanizales commented on docs/_articles/ja/lwc/writing.md
Same comment

2023-08-04 16:34 UTC, CristiCanizales approved these changes
LGTM!

2023-08-04 16:37 UTC, sbudhirajadoc approved these changes

2023-08-08 19:02 UTC, closed without merging