Update cb-start.md
forcedotcom/salesforcedx-vscode pull request #5197
Opened 2023-11-01 06:55 UTC by mmhasanovee

### What does this PR do?

### What issues does this PR fix or reference?
#<Insert GitHub Issue>, @<Insert GUS WI>@

### Functionality Before
<insert gif and/or summary>

### Functionality After
<insert gif and/or summary>

2023-11-01 16:10 UTC, sbudhirajadoc requested changes
Thanks for your PR! Please leave the text in the tip ("dashboard at any time") as is. I'll accept your other changes once you submit the requested change. Thanks!

2023-11-02 22:39 UTC, sbudhirajadoc approved these changes

2023-11-03 18:26 UTC, sbudhirajadoc commented
> @mmhasanovee
can you please sign the agreement so we can move forward to merging your PR? Thank you!

2023-11-06 05:35 UTC, merged

2023-11-06 06:36 UTC, mmhasanovee commented
> > @mmhasanovee
> > can you please sign the agreement so we can move forward to merging your PR? Thank you!

@sbudhirajadoc , 
It's saying "You already signed the CLA on 2023-11-01"