feat: migrate from @salesforce/core v5 -> v6
forcedotcom/salesforcedx-vscode pull request #5332
Opened 2024-01-11 19:10 UTC by daphne-sfdc

### What does this PR do?
Migrates @salesforce/core from v5.3.0 -> v6.4.3

This upgrade means we are able to support Core v6 in our other dependencies, so the following dependencies are also migrated from Core v5 -> v6 in this PR:
1. @salesforce/source-deploy-retrieve - v9.8.4 -> v10.2.5
2. @salesforce/source-tracking - v4.3.0 -> v5.1.3
3. @salesforce/apex-node - v2.1.6 -> v3.0.1
4. @salesforce/templates - v59.0.4 -> v60.1.0
5. jsforce - v2.0.0-beta.28 -> v2.0.0-beta.29

### What issues does this PR fix or reference?
@W-14671437@

### Functionality Before
Extensions monorepo uses v5 of @salesforce/core

### Functionality After
Extensions monrepo uses v6 of @salesforce/core, which means we are now able to pull in new features from our shared libraries

2024-01-11 19:29 UTC, peternhale requested changes

2024-01-11 19:29 UTC, peternhale commented on packages/salesforcedx-sobjects-faux-generator/package.json
> +    "@salesforce/core": "6.4.3",
@daphne-sfdc please bump this to the most recent version of v6. I know its a moving target, but lets try to get this merged being as close to current as possible.

2024-01-11 19:29 UTC, peternhale commented on packages/salesforcedx-sobjects-faux-generator/package.json
> +    "@salesforce/core": "6.4.3",
Probably should visit all of the one to see if they have been bumped

2024-01-11 21:10 UTC, peternhale approved these changes

2024-01-12 22:44 UTC, mingxuanzhangsfdx approved these changes

2024-01-12 22:44 UTC, mingxuanzhangsfdx commented
I tested it manually and it looks good.

2024-01-12 22:47 UTC, merged