fix: capture complete extension load time
forcedotcom/salesforcedx-vscode pull request #5397
Opened 2024-02-05 21:40 UTC by peternhale

- Add utility function to vscode-utils that returns the activation event for a given extension from extension host log
- At the beginning of each extension’s activate function
-- Capture the timestamp of function entry
-- Capture the timestamp of the extension activation event using util from vscode-utils
- Send activation telemetry record with
-- Time spent in activation function (this is the current data)
-- Timestamp of activate function entry
-- Timestamp of extension activation
-- Time spent for activation (activate function exit timestamp - extension activation event timestamp) in milliseconds

AC:

- vscode-utils provides a function that returns the ext host extension activation timestamp for the provided extension id
- sendActivation telemetry method will accept
-- Time spent in activation function (this is the current data)
-- Timestamp of activate function entry
-- Timestamp of extension activation
-- Time spent for activation (activate function exit timestamp - extension activation event timestamp) in milliseconds
- One should be able to visit AppInsights to verify the new data are available in the activation telemetry record

2024-02-08 20:42 UTC, mingxuanzhangsfdx requested changes
It does not work in apex debugger. It is also missed in visualforce & replay debugger.

2024-02-08 20:42 UTC, mingxuanzhangsfdx commented on packages/salesforcedx-vscode-lightning/src/telemetry/index.ts
> +export const telemetryService = TelemetryService.getInstance('salesforcedx-vscode-apex');
Is this the right name for lightning extension?

2024-02-08 20:42 UTC, mingxuanzhangsfdx commented on packages/salesforcedx-vscode-apex/src/telemetry/index.ts
> +export const telemetryService = TelemetryService.getInstance('salesforcedx-vscode-apex');
I do not feel it is necessary to specify a name for the core extensions such as apex & lightning. The reason why we pass in the name is only that e4d is using the telemetryService by salesforcedx-vscode-core. However, extensions in this core repo use their own TelemetryService 
`import { TelemetryService } from '@salesforce/salesforcedx-utils-vscode';` makes it.

2024-02-08 20:42 UTC, mingxuanzhangsfdx commented on packages/salesforcedx-vscode-apex/src/telemetry/index.ts
> +export const telemetryService = TelemetryService.getInstance('salesforcedx-vscode-apex');
Of course, it does not hurt to use in this way. Actually the name is specified during initializeService for now (not ideally).

2024-02-08 21:26 UTC, peternhale commented on packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
> +  public get activationInfo(): ActivationInfo {
This pattern prevents direct property access and forces it through logic.

If we wanted to allow a property's value to change we would add
```
public set activationInfo(activationInfo: ActivationInfo): void {
  // do some validation checks on the value to be stored. Allows the class to control how changes are made
  if (iDontLikeYourChange) {
    throw 'toughLuck';
  }
  this._activationInfo = activationInfo;
}
```

2024-02-08 23:01 UTC, mingxuanzhangsfdx commented on packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
> +  public get activationInfo(): ActivationInfo {
Thanks. Then why did you not use a setter function on line 55?
```
    this._activationInfo = {
      ...this._activationInfo,
      ...extensionInfo,
      activationTime
    };
```

2024-02-15 07:13 UTC, gbockus-sf commented on packages/salesforcedx-vscode-visualforce/package.json
> +    "bundle:extension:build": "esbuild ./src/extension.ts  --bundle --outfile=dist/index.js --format=cjs --platform=node --external:vscode --external:@salesforce/source-tracking --external:@salesforc
whoops...shouldn't have removed --minify.  This was a debugging step

2024-02-15 16:06 UTC, gbockus-sf commented on packages/salesforcedx-vscode-core/src/index.ts
>    };
This object is where you can add modules to expose in the API of the extension.

2024-02-17 15:22 UTC, CristiCanizales requested changes
just a couple of nits

2024-02-17 15:22 UTC, CristiCanizales commented on packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
> +    // on quaility of telemetry data
```suggestion
    // on quality of telemetry data
```

2024-02-17 15:22 UTC, CristiCanizales commented on packages/salesforcedx-utils-vscode/src/helpers/activationTracker.ts
> +    // this code. All needed data have been captured for telementry, so a wait here should have no effect
```suggestion
    // this code. All needed data have been captured for telemetry, so a wait here should have no effect
```

2024-02-17 15:22 UTC, CristiCanizales commented on packages/salesforcedx-utils-vscode/src/helpers/activationTrackerUtils.ts
> + * given an log Uri, this function will return the exthost.log file contents
```suggestion
 * given a log Uri, this function will return the exthost.log file contents
```

2024-02-19 19:51 UTC, CristiCanizales commented
QE notes:
Confirmed the data is being sent to AppInsights ✅ 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/113132642/3264da00-2fa0-49e8-ad8b-a83af9638fe1)

2024-02-21 14:20 UTC, CristiCanizales approved these changes
LGTM!

:shipit:

2024-02-26 17:22 UTC, CristiCanizales approved these changes

2024-03-04 23:28 UTC, mingxuanzhangsfdx approved these changes
LGTM!

2024-03-05 12:53 UTC, merged