feat: Github Actions workflows to automate initial validation of customer Github issues
forcedotcom/salesforcedx-vscode pull request #5614
Opened 2024-05-28 13:58 UTC by daphne-sfdc

### What does this PR do?
Two new Github Actions workflows – **Validate New Issues** and **Validate Updated Issues** that read the content of new Github issues.
- Feature requests submitted using the feature request template are automatically labeled as `type:enhancements`.
- Bug reports are checked for all the required basic info in the bug report template and tagged as `validated` if all required info is present.
- If the required info is missing, the workflows post a comment to ask for the missing info, and then tag the issue with `more information required`.
- If the customer provides an outdated version of the extensions, CLI, or VSCode, the workflows post a comment with instructions to update to the latest version, and then tag the issue with `more information required`.

### What issues does this PR fix or reference?
@W-15525741@

### Functionality Before
The support person has to read through each Github issue and manually ask the customer for more info if the customer did not completely fill out the bug report template.

### Functionality After
The initial validation is done by the new **Validate New Issues** and **Validate Updated Issues** Github Actions workflows, and the support person only needs to look at issues that the workflows have tagged as `validated`.

Notes here: https://salesforce.quip.com/2ralAJ3bZkq5

2024-05-28 16:18 UTC, CristiCanizales requested changes
This is great stuff Daphne! Thanks for all of this. I just have a couple of questions, suggestions and one concern. In summary:
- Do we need all the stuff (commented and uncommented code) for local testing? I just don't think we'll be doing local testing at all for this
- Do users need latest CLI version or just a valid one?
- Please update the date in all the copyrights and the name/author in workflows.
- I feel we're encouraging users too much to create cases, and that would involve SLA's and all that 🥵

2024-05-28 18:44 UTC, daphne-sfdc commented on .github/actions/validate-issue/lib/src/nodeVersions.d.ts
> +//# sourceMappingURL=nodeVersions.d.ts.map
`//# sourceMappingURL` in a \*.d.ts file is a source mapping URL comment. It's used to specify a source map file for the TypeScript declaration file (*.d.ts).  Thus, the comment necessary in this case and should not be removed.

2024-05-28 18:53 UTC, daphne-sfdc commented on .github/workflows/validateUpdatedIssues.yml
> +            We encourage anyone experiencing this issue to do the same to increase the priority. We will keep this issue open for the community to collaborate on.
We only have 4 issues total that are owned by another team, and 2 of them are closed.  I think we should keep issues open for tracking purposes. https://github.com/forcedotcom/salesforcedx-vscode/issues?q=is%3Aissue+label%3A%22status%3Aowned+by+another+team%22

2024-05-28 19:58 UTC, CristiCanizales requested changes

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/check-feature-request/lib/src/index.js
> +        // const issue = JSON.parse(getFile("../mock/sample-context.json"));
```suggestion
```

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/check-feature-request/src/index.ts
> +    // const issue = JSON.parse(getFile("../mock/sample-context.json"));
```suggestion
```

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/validate-issue/lib/src/index.js
> +            // const pluginVersionsRegex = /pluginVersions|Plugin Version:/;
```suggestion
```

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/validate-issue/mock/sample-context.json
do we need this file?

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/validate-issue/src/index.ts
> +      // const pluginVersionsRegex = /pluginVersions|Plugin Version:/;
```suggestion
```

2024-05-28 19:58 UTC, CristiCanizales commented on .github/actions/validate-issue/src/index.ts
> +    function getLatestCliVersion(plugin: string) {
are we using this? If not, please remove it

2024-05-29 16:17 UTC, CristiCanizales approved these changes
Looks good! Thanks for addressing all my comments!

:shipit:

2024-05-29 16:21 UTC, merged