fix: language-server v4.12.0 @W-16395004
forcedotcom/salesforcedx-vscode pull request #5725
Opened 2024-08-17 01:07 UTC by ekashida

### What does this PR do?

Bumps the version of @salesforce/lightning-lsp-common, @salesforce/aura-language-server, and @salesforce/lwc-language-server to add the ability for the language server to update the paths mapping in tsconfig.sfdx.json

https://github.com/forcedotcom/lightning-language-server/pull/594

2024-08-19 12:15 UTC, peternhale requested changes

2024-08-19 12:15 UTC, peternhale commented on .npmrc
> +registry=https://registry.npmjs.org
Please revert the change to `.npmrc`

2024-08-21 16:23 UTC, ekashida commented
Thanks for the review @peternhale. It looks like some of the checks are stalled, any idea what may be going on?

2024-08-21 16:37 UTC, CristiCanizales commented
@ekashida I just kicked the runs with an empty push🙂

2024-08-21 18:42 UTC, peternhale approved these changes

2024-08-21 18:43 UTC, peternhale commented
@ekashida you will need to update your branch with HEAD of develop before we can merge the PR

2024-08-21 19:19 UTC, ekashida commented
@peternhale looks like it's ready to merge!

2024-08-21 20:15 UTC, merged